stages:
     - build

build:
    stage: build
    script:
        - git checkout -b $CI_COMMIT_REF_NAME # Checkout branch explicitly due to build script logic
        - ./build.sh --push
    only:
        - branches
    tags:
        - kubernetes
